' Documentazione: https://plantuml.com/sequence-diagram

@startuml
' START STYLE
skinparam {
	monochrome true
	'shadowing false
}
skinparam sequence {
	participantBackgroundColor white
}
hide footbox
' END STYLE

title Adapter: variante Class Adapter

' Aggiungo delle etichette
participant "tg:TestGoblin" as tg
participant "ga:GoblinAdapter" as ga
participant "pv:PelleVerde" as pv

-> tg: main
activate tg

tg -> ga: tiraFreccia(danno)
activate ga

opt pv == null
	ga -> pv ** : create
end

ga -> pv: scagliaPezzoDiLegno(danno * 10)
activate pv

pv --> ga
deactivate pv

ga --> tg
deactivate ga

deactivate tg

@enduml