' Documentazione: https://plantuml.com/sequence-diagram

@startuml
' START STYLE
skinparam {
	monochrome true
	'shadowing false
}
skinparam sequence {
	participantBackgroundColor white
}
hide footbox
' END STYLE

title Singleton: Balancer - Sequence Diagram

' Aggiungo delle etichette
participant "tb:TestBalancer" as tb
participant ":Balancer" as BB
participant "b:Balancer" as b

' attivo il main
activate tb

' chiamata a Balancer.getInstance()
tb -> BB: getInstance()
activate BB

' chiamata al costruttore se b == null
alt b == null
	BB -> b ** : new
end

' return b (instance)
BB --> tb: b
deactivate BB

' chiamo b.getHost()
tb -> b: getHost()
activate b
b --> tb: host
deactivate b


@enduml